% Calculate return statistics and normality tests for BELEX log returns.

if ~exist('rt', 'var')
    error('BELEX:MissingSeries', ...
        'Run scripts/load_transform.m before this script.');
end

basicStatsRt = basicstat1(rt);

meanRt = basicStatsRt(1);
meanStandardErrorRt = basicStatsRt(2);
varianceRt = basicStatsRt(3);
standardDeviationRt = basicStatsRt(4);
skewnessRt = basicStatsRt(5);
skewnessStandardErrorRt = basicStatsRt(6);
skewnessTestStatisticRt = basicStatsRt(7);
skewnessCriticalValueRt = basicStatsRt(8);
kurtosisRt = basicStatsRt(9);
kurtosisStandardErrorRt = basicStatsRt(10);
kurtosisTestStatisticRt = basicStatsRt(11);
kurtosisCriticalValueRt = basicStatsRt(12);
jarqueBeraStatisticRt = basicStatsRt(13);
jarqueBeraCriticalValueRt = basicStatsRt(14);
skewnessRejectedRt = logical(basicStatsRt(15));
kurtosisRejectedRt = logical(basicStatsRt(16));
jarqueBeraRejectedRt = logical(basicStatsRt(17));
excessKurtosisRt = kurtosisRt - 3;

if skewnessRejectedRt
    skewnessDecisionRt = 'Reject H0';
else
    skewnessDecisionRt = 'Do not reject H0';
end
if kurtosisRejectedRt
    kurtosisDecisionRt = 'Reject H0';
else
    kurtosisDecisionRt = 'Do not reject H0';
end
if jarqueBeraRejectedRt
    jarqueBeraDecisionRt = 'Reject H0';
else
    jarqueBeraDecisionRt = 'Do not reject H0';
end

basicStatisticsRt = table( ...
    meanRt, meanStandardErrorRt, varianceRt, standardDeviationRt, ...
    skewnessRt, skewnessStandardErrorRt, skewnessTestStatisticRt, ...
    skewnessCriticalValueRt, {skewnessDecisionRt}, kurtosisRt, ...
    excessKurtosisRt, kurtosisStandardErrorRt, kurtosisTestStatisticRt, ...
    kurtosisCriticalValueRt, {kurtosisDecisionRt}, ...
    jarqueBeraStatisticRt, jarqueBeraCriticalValueRt, ...
    {jarqueBeraDecisionRt}, ...
    'VariableNames', { ...
    'Mean', 'MeanStandardError', 'Variance', 'StandardDeviation', ...
    'Skewness', 'SkewnessStandardError', 'SkewnessTestStatistic', ...
    'SkewnessCriticalValue', 'SkewnessDecision', 'Kurtosis', ...
    'ExcessKurtosis', 'KurtosisStandardError', ...
    'KurtosisTestStatistic', 'KurtosisCriticalValue', ...
    'KurtosisDecision', 'JarqueBeraStatistic', ...
    'JarqueBeraCriticalValue', 'JarqueBeraDecision'});

scriptPath = mfilename('fullpath');
repositoryRoot = fileparts(fileparts(scriptPath));
tablesDirectory = fullfile(repositoryRoot, 'results', 'tables');
if exist(tablesDirectory, 'dir') ~= 7
    mkdir(tablesDirectory);
end
writetable(basicStatisticsRt, ...
    fullfile(tablesDirectory, 'basic_statistics_rt.csv'));

if skewnessRejectedRt
    if skewnessRt > 0
        asymmetryDescription = 'statistically significant positive (right) asymmetry';
    else
        asymmetryDescription = 'statistically significant negative (left) asymmetry';
    end
    skewnessInterpretation = sprintf([ ...
        'Skewness is %.6g (test statistic %.6g versus critical values +/-%.6g), ' ...
        'so the skewness test rejects symmetry and indicates %s.'], ...
        skewnessRt, skewnessTestStatisticRt, skewnessCriticalValueRt, ...
        asymmetryDescription);
else
    skewnessInterpretation = sprintf([ ...
        'Skewness is %.6g (test statistic %.6g versus critical values +/-%.6g), ' ...
        'so the skewness test does not reject symmetry; the data do not show ' ...
        'statistically significant asymmetry.'], ...
        skewnessRt, skewnessTestStatisticRt, skewnessCriticalValueRt);
end

if kurtosisRejectedRt && excessKurtosisRt > 0
    kurtosisInterpretation = sprintf([ ...
        'Kurtosis is %.6g, giving excess kurtosis of %.6g ' ...
        '(test statistic %.6g versus critical values +/-%.6g). The kurtosis ' ...
        'test rejects Normal kurtosis; the positive excess supports a ' ...
        'leptokurtic distribution with heavy tails relative to the Normal distribution.'], ...
        kurtosisRt, excessKurtosisRt, kurtosisTestStatisticRt, ...
        kurtosisCriticalValueRt);
elseif kurtosisRejectedRt
    kurtosisInterpretation = sprintf([ ...
        'Kurtosis is %.6g, giving excess kurtosis of %.6g ' ...
        '(test statistic %.6g versus critical values +/-%.6g). The kurtosis ' ...
        'test rejects Normal kurtosis, but the non-positive excess does not ' ...
        'support heavy tails relative to the Normal distribution.'], ...
        kurtosisRt, excessKurtosisRt, kurtosisTestStatisticRt, ...
        kurtosisCriticalValueRt);
else
    kurtosisInterpretation = sprintf([ ...
        'Kurtosis is %.6g, giving excess kurtosis of %.6g ' ...
        '(test statistic %.6g versus critical values +/-%.6g). The kurtosis ' ...
        'test does not reject Normal kurtosis, so there is insufficient ' ...
        'evidence of excess kurtosis or heavy tails.'], ...
        kurtosisRt, excessKurtosisRt, kurtosisTestStatisticRt, ...
        kurtosisCriticalValueRt);
end

if jarqueBeraRejectedRt
    normalityInterpretation = sprintf([ ...
        'The Jarque-Bera statistic is %.6g, above its %.6g critical value. ' ...
        'The test rejects Normality at the 5%% level, providing evidence ' ...
        'against a Normal return distribution.'], ...
        jarqueBeraStatisticRt, jarqueBeraCriticalValueRt);
else
    normalityInterpretation = sprintf([ ...
        'The Jarque-Bera statistic is %.6g, not above its %.6g critical value. ' ...
        'The test does not reject Normality at the 5%% level; this is not proof ' ...
        'that the returns are Normal.'], ...
        jarqueBeraStatisticRt, jarqueBeraCriticalValueRt);
end

reportText = sprintf('%s\n%s\n%s\n', skewnessInterpretation, ...
    kurtosisInterpretation, normalityInterpretation);
fprintf('%s', reportText);

reportFile = fullfile(tablesDirectory, ...
    'basic_statistics_rt_interpretation.txt');
reportId = fopen(reportFile, 'w');
if reportId == -1
    error('BELEX:ReportWriteFailed', ...
        'Could not open the basic-statistics interpretation file: %s', ...
        reportFile);
end
fprintf(reportId, '%s', reportText);
fclose(reportId);

clear asymmetryDescription kurtosisInterpretation normalityInterpretation ...
    reportFile reportId reportText repositoryRoot scriptPath ...
    skewnessInterpretation tablesDirectory;
